spring:
  datasource:
    url: jdbc:mysql:///cassys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  http:
    encoding:
      force: true
    charset: UTF-8
    enabled: true
server:
  tomcat:
    uri-encoding: UTF-8

mybatis:
  type-aliases-package: com.jkxy.car.api.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl